version: '3'
services:
  database:
    image: postgres
    restart: always
    container_name: aircos-todo
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: aircos-todo
    ports:
      - 5438:5432
    volumes:
      - ./data:/var/lib/postgresql/data
